### PR TITLE
update syntax for terraform 0.12

### PR DESCRIPTION
**Pull request by roobert**
Quick PR to update syntax for terraform 0.12..

### CODE REVIEW

**Review by prog893 — APPROVED** [review]
Thank you for PR!

Old interpolation syntax (HCL1) was left intentionally to support both 0.11 and 0.12, but newer 0.12 plans throw a lot of warnings when old syntax is there. We waited long enough to break support for 0.11, and I guess we finally should.

When we are ready to ship 0.12-only module (we still have to update README and stuff), we will tag a v2.x.x. 

Thank you again for your contribution!

**Comment by prog893** [comment]
cc: @toVersus just in case

**Comment by roobert** [comment]
Thank you for the modules!

I made this PR since I'm using: baikonur-oss/terraform-aws-fargate-scheduled-task which pulls this module in. I notice that the other module has already been updated to 0.12 syntax. I was looking for a way to override this module to get rid of the warnings but it doesn't look like it would be possible for me to do without forking terraform-aws-fargate-scheduled-task so I settled on opening this PR and hoping for the best :)

**Comment by prog893** [comment]
I will make sure `fargate-scheduled-task` will be updated as soon as possible after v2.x release on this module!

**Review by toVersus — APPROVED** [review]
Thanks, LGTM!

**Comment by prog893** [comment]
Hey @roobert ,

We released v2.0.0 on this module and well as `fargate-scheduled-task` v2.0.2 (using `iam-nofile` v2.0.0). See: `fargate-scheduled-task` v2.0.2 on [Github](https://github.com/baikonur-oss/terraform-aws-fargate-scheduled-task/tree/v2.0.2) and [Registry](https://registry.terraform.io/modules/baikonur-oss/fargate-scheduled-task/aws/2.0.2). Happy terraforming!

**Comment by roobert** [comment]
Thanks so much @prog893! Already updated and it's working perfectly. Thanks again for the great modules!

**Pull request merged**
